name: Setup Tauri
description: Full Tauri build environment (Bun + Rust + Linux deps)

inputs:
  rust-components:
    description: Additional Rust toolchain components
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2

    - uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: bun-${{ runner.os }}-${{ hashFiles('bun.lock') }}
        restore-keys: |
          bun-${{ runner.os }}-

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.rust-components }}

    - uses: swatinem/rust-cache@v2
      with:
        workspaces: src-tauri

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      shell: bash

    - run: bun install --frozen-lockfile
      shell: bash
